monitor=,preferred,auto,1

exec-once = waybar
exec-once = hyprpaper
exec-once = swaync
exec-once = /usr/libexec/polkit-gnome-authentication-agent-1
exec-once = nm-applet --indicator
exec-once = blueman-applet

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
        tap-to-click = yes
    }
    sensitivity = 0
}

general {
    gaps_in = 4
    gaps_out = 6
    border_size = 1
    col.active_border = rgba(3584e4ee)
    col.inactive_border = rgba(595959aa)
    layout = dwindle
    cursor_inactive_timeout = 3
}

decoration {
    rounding = 8
    blur {
        enabled = true
        size = 3
        passes = 1
    }
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes
    bezier = overshot, 0.13, 0.99, 0.29, 1.1
    animation = windows, 1, 4, overshot, popin
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default, slidevert
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

gestures {
    workspace_swipe = on
    workspace_swipe_fingers = 3
}

misc {
    force_default_wallpaper = 0
    vrr = 0
    disable_autoreload = 1
}

windowrule = float, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$

bind = SUPER, Return, exec, foot
bind = SUPER, D, exec, rofi -show drun
bind = SUPER, Q, killactive,
bind = SUPER, M, exit,
bind = SUPER, Space, togglefloating,
bind = SUPER, F, fullscreen,
bind = SUPER, L, exec, hyprlock
bind = SUPER, E, exec, nautilus
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1
bind = SUPER_SHIFT, 1, movetoworkspace, 1
bind = SUPER_SHIFT, 2, movetoworkspace, 2
bind = SUPER_SHIFT, 3, movetoworkspace, 3
bind = SUPER_SHIFT, 4, movetoworkspace, 4
bind = SUPER_SHIFT, 5, movetoworkspace, 5
bind = SUPER_SHIFT, 6, movetoworkspace, 6
bind = SUPER_SHIFT, 7, movetoworkspace, 7
bind = SUPER_SHIFT, 8, movetoworkspace, 8
bind = SUPER_SHIFT, 9, movetoworkspace, 9
bind = SUPER_CTRL, right, workspace, +1
bind = SUPER_CTRL, left, workspace, -1
bind = SUPER_CTRL_SHIFT, right, movetoworkspace, +1
bind = SUPER_CTRL_SHIFT, left, movetoworkspace, -1
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bind = , XF86MonBrightnessUp, exec, brightnessctl s 10%+
bind = , XF86MonBrightnessDown, exec, brightnessctl s 10%-
