background {
    color = rgba(1e1e1eee)
}

input-field {
    monitor =
    size = 250, 40
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.4
    outer_color = rgba(595959ee)
    inner_color = rgba(1e1e1eee)
    font_color = rgba(ffffffee)
    fade_on_empty = true
    placeholder_text = Password...
    fail_text = Auth failed
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    text = $TIME
    font_size = 64
    color = rgba(ffffffee)
    position = 0, 40
    halign = center
    valign = center
}

label {
    text = cmd[update:1800] echo "$(date '+%A, %B %d')"
    font_size = 18
    color = rgba(ccccccff)
    position = 0, -20
    halign = center
    valign = center
}
