name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-iso:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [minimal, desktop, laptop, server]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          use-flakehub: false
      - name: Build ISO ${{ matrix.variant }}
        run: |
          NIXPKGS_ALLOW_BROKEN=1 nix build --impure \
            '.#packages.x86_64-linux.iso-${{ matrix.variant }}'
      - name: Upload ISO ${{ matrix.variant }}
        uses: actions/upload-artifact@v4
        with:
          name: bora-${{ matrix.variant }}
          path: result
          compression-level: 0
